### PR TITLE
Breaking : Manage public authorization on new user

### PR DESCRIPTION
**Pull request by jmjoary**
If we can allow a unlogged user to create an account for our app, we can not allow a unlogged user to get any user in our database for security reason.

So I think it will be better to return a boolean on the account creation. If it is true, then we can logged the user in and provide his account. The app will need to a extra call to the database to get the current user, but it will happened only on user creation.

### CODE REVIEW

**Comment by maxbritto** [comment]
Thanks for the patch!

I'm not sure I understand the goal here.
It seems useful for the user who just created the account to receive his own data back. Especially if the server has modified this data in a hook or something. This function does not allow to fetch an existing user, but only to return what was actually created with this call.
Maybe I am missing something and this could be abused.
Can you give me more info on the risks you see with the `createNewDirectusUser` returning the new user created ?

**Comment by jmjoary** [comment]
When the user create his account, he can not be logged in because his account doesn't exist yet. So to allow the user to get his account data, we have to change the public permissions for the directus user table to see every users as we don't know the new user id.

I think it is safer to like this : 

1. allow the user to create his account,
2. logged the user,
3. get his account data.

My directus user permissions for public role are set like this :
Capture d’écran 2022-09-28 à 18 39 57

When I call the api to create a new user I got this response 
Capture d’écran 2022-09-28 à 18 38 30

As the user is not logged in Directus can't provide his data.

By doing that, we don't have to expose all directus users data via the api. I agree it will do some extra calls to the api but only when the user create his account. So I think it isn't really an issue.

**Comment by jmjoary** [comment]
Hi Maxime,

I have updated my code as discuss yesterday evening.

Kinds regards

**Comment by maxbritto** [comment]
Since the problem could happen with any creation where the user doing the creation has create only access, we should find a fix for all the items.

What about using a generic class so that we can use it for each create call ?
Like this : 
```dart
class DirectusItemCreationResult<T> {
  final bool isSuccess;
  final T? createdItem;

  const DirectusItemCreationResult({required this.isSuccess, this.createdItem});
}
```

This would mean also using it in the `createNewItem` function : 
```dart
Future<DirectusItemCreationResult<Type>> createNewItem<Type>
```

What do you think ?

**Comment by jmjoary** [comment]
Yes it will be a great idea. But it may be better to apply them to the update and delete calls also. It will be more consistent. What do you think ?

I don't get why createdItem is T? as we will provide for most case Map<String, dynamic> type. The developper will have to handle the map to generate his object.

Can you please explain the need on this ?

**Comment by maxbritto** [comment]
> Yes it will be a great idea. But it may be better to apply them to the update and delete calls also. It will be more consistent. What do you think ?

Yes, definitely 👍

> I don't get why createdItem is T? as we will provide for most case Map<String, dynamic> type. The developper will have to handle the map to generate his object.

Right now all the functions require a parsing function as a parameter that transforms the `Map` to a custom model object. Only the `DirectusUser` related functions are not asking for the parsing function because the class is known (`DirectusUser`) and can be parsed internally.

**Comment by jmjoary** [comment]
I have added an abstract class DirectusItem to allow to return object directly. So in the different call we can provide the object type expected and get directly an object in the DirectusWriteItemResult.

I hope I understood your point correctly.

**Comment by jmjoary** [comment]
We have decided to cancel this pull request. A better solution has been found. It will be implemented soon.

**Pull request closed without merging**
